---
title: "The list of beneficial and pathogenic species from log2FC raw abundance data"
author: "Suet Li Hooi"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
setwd("~/AMILI_2022/DOLE")
library(phyloseq)
library(ggplot2)
library(tidyverse)
library(ggsci)

```

```{r}
banana_log2FC <- read.csv('banana_log2FC_t2.csv') %>%
  select(-1) %>%
  separate(Species, into = c('species', 'SGB'), sep = "\\|") %>%
  mutate(species = gsub("s__", "", species)) %>%
  dplyr::rename(Species =species)
  
annotated <- read.csv('annotated_species.csv')

banana_log2FC <- banana_log2FC %>%
  merge(annotated, by = "Species") %>%
  mutate(log2fc = ifelse(Green_Banana_T2 > 0, "Positive log2FC", "Negative log2FC"))
```

```{r}
psmelt_dole_raw <- read.csv('psmelt_dole_raw.csv') %>%
  separate(Species, into = c('species', 'SGB'), sep = "\\|") %>%
  mutate(species = gsub("s__", "", species)) %>%
  dplyr::rename(Species = species) %>% 
  filter(Species %in% banana_log2FC$Species) %>%
  merge(banana_log2FC, by = "Species")
```

```{r, fig.width=12, fig.height=8}
psmelt_dole_raw %>%
  filter(type %in% "beneficial", Group %in% "Green_Banana") %>%
  mutate(Abundance_log = log2(value)) %>%
  ggplot(aes(Timepoint, value, fill = log2fc)) +
  geom_boxplot(show.legend = T) +
  theme_bw() +
  facet_wrap(vars(Species), ncol = 3, scales = "free_y") +
  ylab("Relative abundance") + xlab("Timepoint") +
  ggtitle("Relative abundance of beneficial species for green banana \n with top 15 log2FC from baseline to T2") +
  theme(text = element_text(size=18))
```

```{r, fig.width=12, fig.height=12}
psmelt_dole_raw %>%
  filter(type %in% "pathogenic", Group %in% "Green_Banana") %>%
  mutate(Abundance_log = log2(value)) %>%
  ggplot(aes(Timepoint, value, fill = log2fc)) +
  geom_boxplot(show.legend = T) +
  theme_bw() +
  facet_wrap(vars(Species), ncol = 3, scales = "free_y") +
  ylab("Relative abundance") + xlab("Timepoint") +
  ggtitle("Relative abundance of pathogenic species for green banana \n with top 15 log2FC from baseline to T2") +
  theme(text = element_text(size=18))
```


