---
title: "loop_ggplot_DOLE"
author: "Suet Li Hooi"
date: "`r Sys.Date()`"
output: html_document
---

```{r}

setwd("~/AMILI_2022/DOLE")
library(tidyverse)
library(ggplot2)
library(phyloseq)
library(splitstackshape)
library(reshape2)
library(ggsignif)
library(gridExtra)
library(ggsci)
```

```{r}
#input for the below plots
psmelt_dole_raw <- read.csv('psmelt_dole_raw.csv')
```


```{r, fig.width=12, fig.height=10}
library(ggplot2)

# Create a function that takes filtering parameters as input and generates the plot
generate_plot <- function(data, filter_param, species_filter) {
  filtered_data <- data %>%
    filter(Group %in% filter_param,
           grepl(species_filter, Species)) %>%
    mutate(Abundance_log = log2(value))

  ggplot(filtered_data, aes(Timepoint, value, fill = Timepoint)) +
    scale_fill_manual(values = c("T0" = "grey", "T1" = "lightpink", "T2" = "lightblue")) + 
    geom_bar(stat = "identity") +
    theme_bw() +
    facet_wrap(vars(Subject.ID), ncol = 3, scales = "free_y") +
    ylab("Relative abundance") + xlab("Intervention") +
    ggtitle(paste("Relative abundance of", species_filter, "for", filter_param)) +
    theme(text = element_text(size = 18))
}

# List of different filtering parameters and species filters
filter_params <- c("Green_Banana", "Pineapple", "Control")
species_filters <- c("Bifidobacterium_catenulatum", "Alistipes_onderdonkii", "Eubacterium_rectale", "Holdemanella_biformis", "Mitsuokella_multacida", "Bacteroides_caccae", "Coprococcus_comes","Phascolarctobacterium_succinatutens")

# Create and display plots for each combination of filtering parameters and species filters
for (param in filter_params) {
  for (species_filter in species_filters) {
    plot <- generate_plot(psmelt_dole_raw, param, species_filter)
    print(plot)
  }
}

```

